language: php
 
php:
  - 5.3
  - 5.4
 
before_script:
  - composer self-update
  - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - mv ../cakephp-gravatar-plugin plugins/Gravatar
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - chmod -R 777 app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > app/Config/database.php
 
script:
  - ./lib/Cake/Console/cake test Gravatar View/Helper/GravatarHelper --stderr
 
notifications:
  email: false